---
title: "README"
output: github_document
---

```{r,message=FALSE}
library(tidyverse)
library(nflreadr)
library(arrow)
```

```{r, cache = TRUE,message=FALSE}
datasets <-
    nflreadr::nflverse_releases()[['release_name']]

purrr::walk(
    datasets,~{
        do.call(
            nflreadr::nflverse_download,
            list(
                ... = .x,
                folder_path = "data/",file_type = "parquet")
        )
    }
)
```

```{r}
# View data that's available ----------------------------------------------

fs::dir_ls('data/')

# Weekly rosters ----------------------------------------------------------
nflreadr::dictionary_rosters
data_dir <- arrow::open_dataset("data/weekly_rosters")
data_dir |>
    filter(season==2023L,
           week==19L,
           team=="BUF") |>
    collect() |>
    pivot_wider(
        id_cols = c(team,status),
        names_from = depth_chart_position,
        values_from = full_name
    )

# combine -----------------------------------------------------------------

nflreadr::dictionary_combine
rqdata_dir <- arrow::open_dataset("data/combine")
rqdata_dir |>
    filter(season==2023L,grepl("Buf",draft_team)) |>
    collect()

# injuries -----------------------------------------------------------------

nflreadr::dictionary_injuries
data_dir <- arrow::open_dataset("data/injuries/season=2023/")
data_dir |>
    filter(team=="BUF") |>
    collect()

# play by play -----------------------------------------------------------------

nflreadr::dictionary_pbp
data_dir <- arrow::open_dataset("data/pbp")
data_dir |>
    filter(home_team=="BUF",grepl("2023",game_id),week==19) |>
    select(play_id,game_id,contains('player_name')) |>
    collect() |>
    pivot_longer(
        cols = contains('player_name'),
        names_to = "play_action",
        values_to = "player_name"
    ) |>
    mutate(
        play_id = factor(play_id),
        play_action = stringr::str_remove(play_action,"_player_name"),
        play_action = stringr::str_remove(play_action,"_[0-9]$")
    ) |>
    drop_na()

# nextgen_stats -----------------------------------------------------------------

nflreadr::dictionary_nextgen_stats
data_dir <- arrow::open_dataset("data/nextgen_stats/ngs_receiving.parquet")
data_dir |>
    filter(season==2023L & week==1) |>
    collect()

# snap_counts -----------------------------------------------------------------

nflreadr::dictionary_snap_counts
data_dir <- arrow::open_dataset("data/snap_counts")
data_dir |>
    filter(season==2023L & team=="BUF" & week==19) |>
    collect()

# pbp_participation -----------------------------------------------------------------

nflreadr::dictionary_participation
data_dir <- arrow::open_dataset("data/pbp_participation")
data_dir |>
    filter(season==2023L,possession_team=="BUF") |>
    collect()

generate_dictionary <- function(dat){
    dat |>
        mutate(rowid=1:n()) |>
        pivot_longer(
            cols = -rowid
        )
}

```
